# Generated by Django 6.0.1 on 2026-01-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('pop', 'პოპი'), ('rock', 'როკი'), ('jazz', 'ჯაზი'), ('hiphop', 'ჰიპჰოპ'), ('electronic', 'ელექტრონული'), ('folk', 'ფოლკი'), ('classical', 'კლასიკური'), ('rb', 'R&B'), ('country', 'კანტრი'), ('metal', 'მეტალი')], max_length=50)),
                ('mood', models.CharField(choices=[('happy', 'ბედნიერი'), ('sad', 'სევდიანი'), ('energetic', 'ენერგიული'), ('romantic', 'რომანტიკული'), ('chill', 'მშვიდი'), ('angry', 'გაბრაზებული'), ('focused', 'კონცენტრირებული'), ('party', 'ქეიფი'), ('workout', 'ვარჯიში'), ('travel', 'მგზავრობა')], max_length=50)),
                ('energy', models.FloatField(default=0.5, help_text='0-1 დიაპაზონში')),
                ('valence', models.FloatField(default=0.5, help_text='0-1 დიაპაზონში, პოზიტიურობა')),
                ('danceability', models.FloatField(default=0.5, help_text='0-1 დიაპაზონში')),
                ('tempo', models.IntegerField(default=120, help_text='BPM')),
                ('duration', models.IntegerField(default=180, help_text='წამებში')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True)),
                ('duration_listened', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('mood_when_listened', models.CharField(choices=[('happy', 'ბედნიერი'), ('sad', 'სევდიანი'), ('energetic', 'ენერგიული'), ('romantic', 'რომანტიკული'), ('chill', 'მშვიდი'), ('angry', 'გაბრაზებული'), ('focused', 'კონცენტრირებული'), ('party', 'ქეიფი'), ('workout', 'ვარჯიში'), ('travel', 'მგზავრობა')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
